language: node_js
node_js:
  - "10"
services:
  - docker
script:
  - travis_wait docker build -t discovery:build .
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh master
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh release
  on:
    tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/
