name: Docker test

on:
  pull_request:
    branches:
      - master

jobs:
  dev:
    name: Test Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build .